mercure:
    hubs:
        default:
            url: 'http://127.0.0.1:8000'
            public_url: 'http://127.0.0.1:8000/notification/publish'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'